export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';
export const GET_RELATED_RECIPE_SUCCESS = 'GET_RELATED_RECIPE_SUCCESS';
export const POST_RECIPE_SUCCESS = 'POST_RECIPE_SUCCESS';

export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

export const IS_LOAD_MORE = 'IS_LOAD_MORE';


export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
