export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const LOAD_RECIPE_SUCCESS = 'LOAD_RECIPE_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';